http.mappers.json-pretty-print: true
error.whitelabel.enabled: false

server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 0

spring:
  application.name: springmvc-example
  config.name: springmvc-example
  mandatoryFileEncoding: UTF-8

  main:
    web-environment: true
    show-banner: true
    log-startup-info: false

  jpa.show-sql: false

  thymeleaf.cache: true

---
spring.profiles: default

spring:
  datasource:
    platform: h2
    url: "jdbc:h2:${java.io.tmpdir}/springmvc-example;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE"
  jpa:
    show-sql: false
    database: H2
    database-platform: H2
    cache.use_query_cache: true

spring.thymeleaf.cache: false

---
spring.profiles: postgresql

spring:
  datasource:
    url: "jdbc:postgresql:${USER}"
    platform: postgresql
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    hibernate.ddl-auto: none

server.address: 0.0.0.0
