spring:
  application.name: springmvc-example
  config.name: springmvc-example
  mandatoryFileEncoding: UTF-8

  main:
    web-environment: true
    show-banner: true
    log-startup-info: false

  jpa.show-sql: false

  thymeleaf.cache: true

server:
  port: 8080
  address: 127.0.0.1
  sessionTimeout: 0

---
spring.profiles: default

spring.jpa.database: H2
spring.datasource.platform: h2
spring.thymeleaf.cache: false

---
spring.profiles: postgresql

spring:
  datasource:
    platform: postgresql
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    generate-ddl: false
    hibernate.ddl-auto: none

server.address: 0.0.0.0

---
spring.profiles: mysql

spring:
  datasource:
    platform: mysql
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: false
    hibernate.ddl-auto: none

server.address: 0.0.0.0
